//FORMAT = https://drive.google.com/uc?export=view&id=FILE_ID

List<String> urls =[
  
];

List<String> songName = [
  'Talk About Yesterday',
  'Neon Grace',
  'Mirror Lake',
  'Drifted',
  'I Slept Through Winter',
  'Plastic Heaven',
  'Songs For Rain',
  'Velvet Crime',
  'Cool Romance',
  'About To Die',
  'Ghosting',
  'Backspace',
  'Now We Drift',
  'Semicolon',
  'Paper Stars',
  'Exit Signal',
  'We Never Said Goodbye',
  'Silhouette',
  'Just Kids With Umbrellas',
  'Slowburn',
  'Made You Forget',
  'Love Means Nothing',
  'Lunar Static',
  'Meet Me In October',
  'False Memory',
  'Woke Up Blue',
  'Goldline',
  'Kisses In Reverse',
  'Under Fake Skies',
  'Soft Collapse',
  'I Remember The Velvet',
  'Songs For Rain',
  'Opaleye',
  'They Danced Like Smoke',
  'We Are Just Static',
  'Nothing Feels Right',
  'She Had No Face',
  'Before The Glow',
  'Skintone',
  'This Ends In Silence',
  'Dream Museum',
  'Distant Maybe',
  'Freeze',
  'Behind Cold Eyes',
  'Sunlight Theory',
  'Night Shampoo',
];

List<String> songName1 = [
  'Meet Me In October',
  'Goldline',
  'I Remember The Velvet',
  'We Are Just Static',
  'She Had No Face',
  'This Ends In Silence',
  'Freeze',
];
